/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx-theme.ts
 * Command: astryx theme build lib/astryx-theme.ts --out theme/astryx-theme.css
 * CLI: @astryxdesign/cli@0.3.0
 * Core: @astryxdesign/core@0.3.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
