/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/astryx-theme.ts
 * Command: astryx theme build lib/astryx-theme.ts --out theme/astryx-theme.css
 * CLI: @astryxdesign/cli@0.4.2
 * Core: @astryxdesign/core@0.4.2
 */

/// <reference path="./rezisaktiva.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const rezisaktivaTheme: DefinedTheme;
